#!/usr/bin/env bash

set -e

printf '\n\nRunning updateDatabase scripts...'
php /var/www/html/LEAF_Nexus/scripts/updateDatabase.php /LEAF_Nexus/
php /var/www/html/LEAF_Request_Portal/scripts/updateDatabase.php /LEAF_Request_Portal/

exec "$@"
