#!/usr/bin/env bash

set -e

# Sleep to run after MySQL container start
bash -xc 'until nc mysql 3306; do echo -n . ; sleep 1; done'

sleep 5

printf '\n\nRunning updateDatabase scripts...'
php /var/www/html/LEAF_Nexus/scripts/updateDatabase.php /LEAF_Nexus/
php /var/www/html/LEAF_Request_Portal/scripts/updateDatabase.php /LEAF_Request_Portal/

printf '\n\nRunning composer install...'
cd /var/www/html/test && composer install

printf '\n\nRunning composer install...'
cd /var/www/html/test/prepend && composer install

printf '\n\nRunning composer install...'
cd /var/www/html && composer install

exec "$@"
