apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ECR_REPO}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
    - imageName: changeme
      workspace: .
      docker:
        dockerfilePath: docker/php/Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
  - name: dev
    build:
      tagPolicy:
        envTemplate:
          template: "{{.DOCKER_REGISTRY}}/{{.ECR_REPO}}:{{.JOB_NAME}}-{{.DIGEST_HEX}}"
      artifacts:
        - docker: {}
      local: {}
    deploy:
      helm:
        releases:
          - name: "{{.APP_NAME}}"
            chartPath: "charts/{{.APP_NAME}}"
            setValueTemplates:
              image.repository: "{{.DOCKER_REGISTRY}}/{{.ECR_REPO}}"
              image.tag: "{{.JOB_NAME}}-{{.DIGEST_HEX}}"