version: "3.9"

services:
  leaf-php-8:
    image: pelentan/leaf-swarm:production
    env_file:
      - ./env_files/globals_swarm.env
        # - ./env_files/globals_swarm_prod.env
      # - ./env_files/secrets.env

    volumes:
      - /mnt/leaf/:/var/www/
    command: 'source /startup.sh'
    networks:
      - leaf
    # environment:
    #   - DATABASE_PASSWORD=/run/secrets/db_password
    deploy:
      mode: replicated
      replicas: 1
    sysctls:
      net.ipv4.ip_local_port_range: "15000 64000"
    # configs:
    #   - source: entrypoint
    #     target: ./etc/init.d/ss.sh
    #     mode: 0777
    # entrypoint: ["/etc/init.d/ss.sh","/startup.sh"]


    secrets:
      - source: leaf_key
        target: /etc/ssl/certs/leaf.key
      - source: leaf_pem
        target: /etc/ssl/certs/leaf.pem
      - source: leaf_pem
        target: /etc/ssl/certs/test_leaf.pem
      - source: db_password
      - source: db_host
      - source: db_admin
      - source: krb_user
      - source: krb_pass
      - source: cdw_user
      - source: cdw_host
      - source: cdw_pass
      - source: cipher_key
        # - source: db_host_ip

volumes:
  leaf-vol:
    external: true
  leaf-vol-html:
    external: true

networks:
  leaf:
    external: false

secrets:
  leaf_key:
    external: true
  leaf_pem:
    external: true
  db_password:
    external: true
  db_host:
    external: true
  db_admin:
    external: true
  krb_user:
    external: true
  krb_pass:
    external: true
  cdw_user:
    external: true
  cdw_host:
    external: true
  cdw_pass:
    external: true
  cipher_key:
    external: true
      #db_host_ip:
      # external: true
