FROM maven:3.8.6-jdk-11

WORKDIR /apps/qa
RUN chmod -R 777 /apps/qa

# Install tools.
RUN apt-get update -y && apt-get install -y wget unzip && \
    apt-get install -y tzdata && \
    apt-get clean

# Install dependencies for Chrome.
RUN apt-get update && apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 \
    libatk1.0-0 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libglib2.0-0 libnspr4 libnss3 \
    libpango-1.0-0 libpangocairo-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 \
    libxext6 libxfixes3 libxrandr2 libxrender1 xdg-utils libu2f-udev

# Download and install Chrome version 114.0.5735.90.
RUN wget -q -O /tmp/google-chrome-stable_114.0.5735.90-1_amd64.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_123.0.6312.58-1_amd64.deb && \
    dpkg -i /tmp/google-chrome-stable_114.0.5735.90-1_amd64.deb && \
    apt-get install -f -y && \
    rm /tmp/google-chrome-stable_114.0.5735.90-1_amd64.deb

# Install ChromeDriver.
RUN wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -P /tmp/ && \
    unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/ && \
    rm /tmp/chromedriver_linux64.zip && \
    chmod +x /usr/local/bin/chromedriver

ENV env_browser_param=Chrome

# Copy source code and pom file.
COPY . .

# Build and execute tests
#CMD mvn test -Dsurefire.suiteXmlFiles=TestFormsWorkflow.xml
