START TRANSACTION;

ALTER TABLE `employee` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `employee_data` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `employee_data_history` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `employee_privileges` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `indicator_privileges` CHANGE `UID` `UID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `group_privileges` CHANGE `UID` `UID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `position_privileges` CHANGE `UID` `UID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `relation_employee_backup` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `relation_employee_backup` CHANGE `backupEmpUID` `backupEmpUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `relation_group_employee` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;
ALTER TABLE `relation_position_employee` CHANGE `empUID` `empUID` MEDIUMINT UNSIGNED NOT NULL;


UPDATE `settings` SET `data` = '3872' WHERE `settings`.`setting` = 'dbversion';
COMMIT;
