name: Run automated tests manually

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Choose The Test to Run'
        required: true
        options:
          - 'Form Workflow'
          - 'abcd'
jobs:
  run-automated-tests:
    runs-on: ubutnu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: run tests
        run: |
          cd test/Test-Automation
          declare -A map(["Form Workflow"]="test.java.formWorkflow.formWorkflow_Test" ["abcdc"]="xml name2" ["testname3]="xml3")
          SCRIPT=${map["${{inputs.command }}"]} docker compose up


