name: Run automated tests on push to master

on:
  push:
    branches:
      - master
jobs:
  run-sanity-automated-tests-on-push-to-main:
    runs-on: ubutnu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: run tests
        run: |
          cd test/Test-Automation
          SCRIPT=test.java.formWorkflow.formWorkflow_Test docker compose up

  run-regression-automated-tests-on-push-to-main:
    runs-on: ubutnu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: run tests
        run: |
            cd test/Test-Automation
            SCRIPT=test.java.formWorkflow.formWorkflow_Test docker compose up